# Generated by Django 3.1.6 on 2021-05-29 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CPTCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpt_code', models.CharField(max_length=255)),
                ('cpt_description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'CPTCodes',
            },
        ),
        migrations.CreateModel(
            name='CPTCodeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'CPT Code Categories',
                'db_table': 'CPTCodeCategories',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='DistrictCouncil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'DistrictCouncils',
            },
        ),
        migrations.CreateModel(
            name='Exemption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Exemptions',
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('facility_hfr_code', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=1)),
                ('district_council', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MasterData.districtcouncil')),
            ],
            options={
                'verbose_name_plural': 'Facilities',
                'db_table': 'facility',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Gender',
            },
        ),
        migrations.CreateModel(
            name='ICD10Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icd10_code', models.CharField(max_length=255)),
                ('icd10_description', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'ICD10 Codes',
                'db_table': 'ICD10Codes',
            },
        ),
        migrations.CreateModel(
            name='ICD10CodeCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'ICD10 Code Categories',
                'db_table': 'ICD10CodeCategories',
            },
        ),
        migrations.CreateModel(
            name='Payer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Payers',
            },
        ),
        migrations.CreateModel(
            name='PlaceOfDeath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Places Of Death',
                'db_table': 'PlacesOfDeath',
            },
        ),
        migrations.CreateModel(
            name='ServiceProviderRanking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ServiceProviderRankings',
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Zones',
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('local_ward_id', models.CharField(max_length=100)),
                ('local_ward_description', models.CharField(max_length=255)),
                ('number_of_beds', models.IntegerField()),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MasterData.department')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MasterData.facility')),
            ],
            options={
                'db_table': 'Wards',
            },
        ),
        migrations.CreateModel(
            name='ServiceProviderRankingMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_service_provider_ranking_id', models.CharField(max_length=255)),
                ('local_service_provider_ranking_description', models.CharField(max_length=255)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MasterData.facility')),
                ('service_provider_ranking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MasterData.serviceproviderranking')),
            ],
            options={
                'db_table': 'ServiceProviderRankingMappings',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MasterData.zone')),
            ],
            options={
                'db_table': 'Regions',
            },
        ),
        migrations.CreateModel(
            name='PlaceOfDeathMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_place_of_death_id', models.CharField(max_length=255)),
                ('local_place_of_death_description', models.CharField(max_length=255)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MasterData.facility')),
                ('place_of_death', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MasterData.placeofdeath')),
            ],
            options={
                'db_table': 'PlaceOfDeathMappings',
            },
        ),
        migrations.CreateModel(
            name='PayerMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_payer_id', models.CharField(max_length=255)),
                ('local_payer_description', models.CharField(max_length=255)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MasterData.facility')),
                ('payer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MasterData.payer')),
            ],
            options={
                'db_table': 'PayerMappings',
            },
        ),
        migrations.CreateModel(
            name='ICD10SubCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icd10_sub_code', models.CharField(max_length=255)),
                ('icd10_sub_code_description', models.CharField(max_length=255)),
                ('icd10_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MasterData.icd10code')),
            ],
            options={
                'verbose_name_plural': 'ICD10 SubCodes',
                'db_table': 'ICD10SubCodes',
            },
        ),
        migrations.CreateModel(
            name='ICD10CodeSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('icd_10_code_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MasterData.icd10codecategory')),
            ],
            options={
                'verbose_name_plural': 'ICD10 Code Sub Categories',
                'db_table': 'ICD10CodeSubCategories',
            },
        ),
        migrations.AddField(
            model_name='icd10code',
            name='icd_10_code_sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MasterData.icd10codesubcategory'),
        ),
        migrations.CreateModel(
            name='GenderMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_gender_description', models.CharField(max_length=50)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MasterData.facility')),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MasterData.gender')),
            ],
            options={
                'db_table': 'GenderMappings',
            },
        ),
        migrations.CreateModel(
            name='ExemptionMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_exemption_id', models.CharField(max_length=255)),
                ('local_exemption_description', models.CharField(max_length=255)),
                ('exemption', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MasterData.exemption')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MasterData.facility')),
            ],
            options={
                'db_table': 'ExemptionMappings',
            },
        ),
        migrations.AddField(
            model_name='districtcouncil',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MasterData.region'),
        ),
        migrations.CreateModel(
            name='DepartmentMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_department_id', models.CharField(max_length=255)),
                ('local_department_description', models.CharField(max_length=255)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MasterData.department')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MasterData.facility')),
            ],
            options={
                'db_table': 'DepartmentMappings',
            },
        ),
        migrations.CreateModel(
            name='CPTCodeSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('cpt_code_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MasterData.cptcodecategory')),
            ],
            options={
                'verbose_name_plural': 'CPT Code Sub Categories',
                'db_table': 'CPTCodeSubCategories',
            },
        ),
        migrations.CreateModel(
            name='CPTCodesMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_code', models.CharField(max_length=255)),
                ('cpt_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MasterData.cptcode')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MasterData.facility')),
            ],
            options={
                'db_table': 'CPTCodesMappings',
            },
        ),
        migrations.AddField(
            model_name='cptcode',
            name='cpt_code_sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MasterData.cptcodesubcategory'),
        ),
    ]
